spring.application.name=CanchaFacil

# Puerto en el que arranca la aplicacion
server.port=8080

# En desarrollo desactivamos la cache para ver los cambios del HTML al guardar
spring.thymeleaf.cache=false
